name: script-executer

on:
  push:
  workflow_dispatch:

jobs:
  Script-executer:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
      - name: Show container files
        run: ls -la
      - name: Make file executable
        run: chmod +x its-me.sh
      - name: Execute script 
        run: ./its-me.sh
    
